<a href="https://colab.research.google.com/github/jinisaweaklearner/DS-ML-Paper-Note-Code/blob/master/src/keras/dot_layer_and_multiply_layer_in_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import keras
import numpy as np

# Dot Layer

### example 1

In [27]:
x = np.arange(10).reshape(5, 2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
y = np.arange(10, 20).reshape(5, 2)
y

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [32]:
"""
0*10 + 1*11 = 11
2*12 + 3*13 = 63
"""
keras.layers.Dot(axes=1)([x, y])

<tf.Tensor: shape=(5, 1), dtype=int64, numpy=
array([[ 11],
       [ 63],
       [131],
       [215],
       [315]])>

### example 2

In [37]:
x = np.arange(10).reshape(1, 5, 2)
x

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]])

In [38]:
y = np.arange(10, 20).reshape(1, 2, 5)
y

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [39]:
"""
0*10+2*11+4*12+6*13+8*14 = 260
"""
keras.layers.Dot(axes=(1,2))([x, y])

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[260, 360],
        [320, 445]]])>

# Multiply layer

In [42]:
np.arange(5).reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [41]:
np.arange(5, 10).reshape(5, 1)

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [40]:
"""
0*5=0
1*6=6
"""
keras.layers.Multiply()([np.arange(5).reshape(5, 1),np.arange(5, 10).reshape(5, 1)])

<tf.Tensor: shape=(5, 1), dtype=int64, numpy=
array([[ 0],
       [ 6],
       [14],
       [24],
       [36]])>

In [48]:
x1 = np.arange(10).reshape(5, 2)
x1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [47]:
x2 = np.arange(10, 20).reshape(5, 2)
x2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [49]:
"""
0 * 10 = 0
1 * 11 = 11
"""
keras.layers.Multiply()([x1, x2])

<tf.Tensor: shape=(5, 2), dtype=int64, numpy=
array([[  0,  11],
       [ 24,  39],
       [ 56,  75],
       [ 96, 119],
       [144, 171]])>